### ISSUE TITLE
使用该插件会导致Chrome浏览器崩溃

### ISSUE THREAD

**Issue by Dangjia** [xjflyttp/yii2-uploadify-widget#4]
你好，又来打扰你了。
在之前的几个form中使用该插件，一直正常，但是最近的两个form使用该插件，却会引起Chrome浏览器崩溃，界面如同：http://blog.csdn.net/gaojinshan/article/details/38821897 或 http://blog.sina.com.cn/s/blog_69398ed90102v7bo.html

以上是我搜索到的，根据网页上的内容说是uploadify插件引起的，所以我在引起chrome浏览器崩溃的form中把有关uploadify的widget代码删除，发现不会有浏览器崩溃现象。所以基本确定是这个widget引起的，请问你有什么好的解决方案吗？

**Comment by xjflyttp** [comment]
切到dev-master

Chrome Version 40.0.2214.111 (64-bit)
我这边随手试了几下暂时没问题

你试试看吧

PS: Action的变量跟dropzone那边同步了 有一些改变，如果有问题 可以看一下readme

**Comment by Dangjia** [comment]
你好，我注意到页面中加载uploadify插件的flash文件加载了3次，url是一模一样的，前两次的状态是canceled，是不是跟这个有关呢？

![](http://ww2.sinaimg.cn/mw690/005VOYI6tw1epwxs4gcjtj30w5053dhc.jpg)

**Comment by xjflyttp** [comment]
http://www.uploadify.com/demos/
你看一下官方demo
