### ISSUE TITLE
Closure doesn't work

### ISSUE THREAD

**Issue by koxu1996** [xjflyttp/yii2-uploadify-widget#5]
Code from example is outputting error:

PHP Recoverable Error – yii\base\ErrorException
Argument 1 passed to frontend\controllers\FileController::frontend\controllers\{closure}() must be an instance of frontend\controllers\UploadAction, instance of xj\uploadify\UploadAction given

**Comment by xjflyttp** [comment]
hi
you can ignore $action type.
it works.

```php
function($action)
{
//something
}
```

**Comment by koxu1996** [comment]
So, update README or merge my commit.

**Comment by xjflyttp** [comment]
README updated.
thank you .
