### ISSUE TITLE
Exceptions does not terminate upload.

### ISSUE THREAD

**Issue by koxu1996** [xjflyttp/yii2-uploadify-widget#7]
I added:
'beforeValidate' => function($action) {
throw new Exception('Test error');
},
File is uploading normally, but should be cancelled instantly, because of error.

**Comment by xjflyttp** [comment]
//JsOptions
```php
'onUploadSuccess' => <<<EOF
function(file, data, response) {
    console.log(data);
EOF
```

you will recv
```json
{"error":true,"msg":"test error"}
```

**Comment by koxu1996** [comment]
I see that 'beforeValidate' is executed after completed upload.
Luckily there is 'onUploadStart' in jsOption. Thanks

**Comment by xjflyttp** [comment]
Can not terminate frontend swf upload by backend action  ..
because  backend action start after swf do upload success...
