### ISSUE TITLE
一条记录修改时，怎么把图片带过来呢？

### ISSUE THREAD

**Issue by phpcws** [xjflyttp/yii2-uploadify-widget#8]
你好，使用您的上传插件时，修改记录时，图片带不过来，如何处理呢？我使用的是version 2.0。
如有打扰，请原谅，谢谢....

**Comment by xjflyttp** [comment]
上传后把图片路径通过 $action->output数组进行传递
```php
 'afterSave' => function (UploadAction $action) {
    $action->output['fileUrl'] = $action->getWebUrl();
    //$action->getFilename(); // "image/yyyymmddtimerand.jpg"
    //$action->getWebUrl(); //  "baseUrl + filename, /upload/image/yyyymmddtimerand.jpg"
    //$action->getSavePath(); // "/var/www/htdocs/upload/image/yyyymmddtimerand.jpg"
},
```
在客户端通过onUploadSuccess回调的data进行获取这个图片的路径
```
'onUploadSuccess' => "function(file, data, response) {
    data = JSON.parse(data);
    console.log(data.fileUrl);
}"
```

修改记录还是新增记录对于这个扩展来说都是透明的.

**Comment by phpcws** [comment]
@xjflyttp 好的，感谢您的回答，我再尝试下，非常谢谢！！！

**Comment by kunx-edu** [comment]
两个问题
第一个是:在给的demo中,控制器部分version2怎么有两个format
第二个是:如何获取带有域名的绝对路径,目前获取的路径没有域名部分.

感谢

**Comment by xjflyttp** [comment]
两个format是演示支持两种不同形式的调用，选一个就可以了，

至于完整路径，配置的时候有一个baseUrl，配合demo中
$action->getWebUrl();即可获得完整路径，想带域名，只需要对baseUrl赋予正确域名路径 getWebUrl方法就会自行组合

2016年8月13日 00:03，"kunx-edu" <notifications@github.com>写道：

**Comment by kunx-edu** [comment]
我看了一下，@web别名返回的是空字符串，这个怎么解决呢？

感谢回复，祝一切顺利!

发自我的 iPhone

**Comment by xjflyttp** [comment]
@web是框架预设的路径，你的app部署于http://www.test.com/就是空，如果部署在http://www.test.com/test就会返回/test
,因此你要完整路径就使用Url:base(true)去替代他

2016年8月13日 11:23，"kunx-edu" <notifications@github.com>写道：

**Comment by kunx-edu** [comment]
感谢你的回复，由于属性只能使用直接量，我昨天通过actions配置中拼凑了url base

现在正在解决通过activeform的field布局样式的问题


感谢你。祝一切顺利


发自我的 iPhone
