### ISSUE TITLE
如何添加额外属性

### ISSUE THREAD

**Issue by kunx-edu** [xjflyttp/yii2-uploadify-widget#9]
如果我想要添加额外属性在节点上,比如demo-data id等属性,然后通过js获取,请问如何添加属性
我在options中指定了,但是并没有用

> echo $form->field($model, 'image')->widget(xj\uploadify\Uploadify::className(), [
    'url'       => yii\helpers\Url::to(['s-upload']),
    'csrf'      => true,
    'renderTag' => true,
    **'options'=>[
        'id'=>'abc',
        'a'=>'aaa'
    ],**
    'jsOptions' => [
        'width'           => 120,
        'height'          => 40,
        'buttonText'      => '选择文件',
        'buttonClass'=>'bg-primary',
        'onUploadError'   => new JsExpression(<<<EOF
function(file, errorCode, errorMsg, errorString) {
    console.log('The file ' + file.name + ' could not be uploaded: ' + errorString + errorCode + errorMsg);
}
EOF
        ),
        'onUploadSuccess' => new JsExpression(<<<EOF
function(file, data, response) {
    data = JSON.parse(data);
    if (data.error) {
        console.log(data.msg);
    } else {
        console.log(data.fileUrl);
    }
}
EOF
        ),
    ]
]);

**Comment by xjflyttp** [comment]
id修改无效是因为由form传入，id是统一由框架提供的方法生成，用于匹配label和input配对，你可以用Html:getInputId($model,
$attribute)获得生成的实际id来操作，或者渲染一个标准的fileInput再用扩展外挂js进去，这样也比较干净

2016年8月13日 下午1:46，"kunx-edu" <notifications@github.com>写道：

**Comment by kunx-edu** [comment]
那我demo中的a属性呢,也没有加进去...

感谢回复
祝一切顺利



许坤
不抱怨，不推诿，找方法，解决问题

 
发件人： n0tYet
发送时间： 2016-08-13 17:58
收件人： xjflyttp/yii2-uploadify-widget
抄送： kunx-edu; Author
主题： Re: [xjflyttp/yii2-uploadify-widget] 如何添加额外属性 (#9)
id修改无效是因为由form传入，id是统一由框架提供的方法生成，用于匹配label和input配对，你可以用Html:getInputId($model, 
$attribute)获得生成的实际id来操作，或者渲染一个标准的fileInput再用扩展外挂js进去，这样也比较干净 

2016年8月13日 下午1:46，"kunx-edu" <notifications@github.com>写道：

**Comment by xjflyttp** [comment]
因为你看的是运行时状态，
当你看php输出的源码就会发现a=aaa是存在的，
只是因为uploadify的js进行了替换。

要理解这个插件其实跟你的model属性关系不大，
并不是在提交form的时候post文件内容，
所以我建议你用原生的file渲染表单，
再用uploadify去外挂进去

**Comment by kunx-edu** [comment]
你指的是demo中的这种写法么?在options中写自定义内容?:
//外部TAG
**echo Html::fileInput('test', NULL, ['id' => 'test']);**
**echo Uploadify::widget**([
    'url' => yii\helpers\Url::to(['s-upload']),
    'id' => 'test',
    'csrf' => true,
    'renderTag' => false,
**'options'=>['a'=>'aaa','b'=>'bbb'],**
    'jsOptions' => [
        'width' => 120,
        'height' => 40,
        'onUploadError' => new JsExpression(<<<EOF
function(file, errorCode, errorMsg, errorString) {
    console.log('The file ' + file.name + ' could not be uploaded: ' + errorString + errorCode + errorMsg);
}
EOF
),
        'onUploadSuccess' => new JsExpression(<<<EOF
function(file, data, response) {
    data = JSON.parse(data);
    if (data.error) {
        console.log(data.msg);
    } else {
        console.log(data.fileUrl);
    }
}
EOF
),
    ]
]);

**Comment by xjflyttp** [comment]
```php
echo $form->field($model, 'image')->fileInput();
echo Uploadify::widget([
    'url' => yii\helpers\Url::to(['s-upload']),
    'attribute' => 'image',
    'model' => $model,
........................
]);
```
不要再对那个节点动脑筋啦，file节点，你放什么进去其实都是会被js替换成swf。
要附加什么属性就另外registerJs()或者加个hidden之类的tag就可以了

**Comment by kunx-edu** [comment]
在你刚刚给的案例中,发现attribute和model并没有起作用.
我大致明白了你的意思,如果想要附加额外的属性,就使用Html类库直接输出一个控件,设定属性,然后用uploadify变成一个swf即可,比如:
另外uploadify找到这个节点通过id属性,别的都不好使

echo $form->field($model, 'image')->fileInput(['test'=>'aaa',**'id'=>'image'**]);
echo xj\uploadify\Uploadify::widget([
    'url' => yii\helpers\Url::to(['s-upload']),
    **'id' => 'image',**
    'csrf' => true,
    **'renderTag' => false,**
    'jsOptions' => [
        'width' => 120,
        'height' => 40,
        'onUploadError' => new JsExpression(<<<EOF
function(file, errorCode, errorMsg, errorString) {
    console.log('The file ' + file.name + ' could not be uploaded: ' + errorString + errorCode + errorMsg);
}
EOF
),
        'onUploadSuccess' => new JsExpression(<<<EOF
function(file, data, response) {
    data = JSON.parse(data);
    if (data.error) {
        console.log(data.msg);
    } else {
        console.log(data.fileUrl);
    }
}
EOF
),
    ]
]);

**Comment by kunx-edu** [comment]
好的,如你所说,我通过以下方式实现了想要的结果.
echo $form->field($model, 'image')->hiddenInput(['abc'=>'abcdefg']);
echo $form->field($model, 'image')->widget(xj\uploadify\Uploadify::className(), [
    'url'       => yii\helpers\Url::to(['s-upload']),
    'csrf'      => true,
    'renderTag' => true,
    'id'=>'a',
    'jsOptions' => [
        'width'           => 120,
        'height'          => 40,
        'buttonText'      => '选择文件',
        'buttonClass'=>'bg-primary',
        'onUploadError'   => new JsExpression(<<<EOF
function(file, errorCode, errorMsg, errorString) {
    console.log('The file ' + file.name + ' could not be uploaded: ' + errorString + errorCode + errorMsg);
}
EOF
        ),
        'onUploadSuccess' => new JsExpression(<<<EOF
function(file, data, response) {
    data = JSON.parse(data);
    if (data.error) {
        console.log(data.msg);
    } else {
        console.log(data.fileUrl);
        $('#articles-image').val(data.fileUrl)
    }
}
EOF
        ),
    ]
]);


非常感谢!
祝一切顺利

**Comment by xjflyttp** [comment]
nice
